In [1]:
import numpy as np

In [2]:
arr = np.arange(100)/100

In [3]:
arr

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [4]:
arr[:5]

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [5]:
avg = arr.mean()

In [6]:
avg

np.float64(0.49499999999999994)

In [10]:
arr = np.arange(100000)

In [11]:
arr.mean()

np.float64(49999.5)

In [12]:
arr = np.array([1,2,3,4,5])

In [13]:
arr.ndim

1

In [14]:
arr.shape

(5,)

In [16]:
arr_2d = np.array([[1,2],[3,4]])

In [17]:
arr_2d

array([[1, 2],
       [3, 4]])

In [18]:
arr_2d.ndim

2

In [19]:
arr_2d.shape

(2, 2)

In [20]:
arr_2d.size

4

In [25]:
arr_3d = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]],
    [
        [0,1,2],
        [5,4,2],
        [9,8,7]]
])

In [26]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [5, 4, 2],
        [9, 8, 7]]])

In [27]:
arr_3d.shape

(2, 3, 3)

In [28]:
arr_3d.ndim

3

In [29]:
arr_3d.size

18

In [39]:
np.zeros((3,3,3),dtype = 'int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [41]:
np.full((3,3,3),fill_value = 1, dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [43]:
np.arange(0,5,0.1,'float')

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [45]:
np.arange(11, dtype = 'float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
np.random.randint(low = 1, high = 10, size = (3,3,3))

array([[[9, 8, 3],
        [2, 5, 8],
        [4, 4, 1]],

       [[5, 7, 9],
        [1, 2, 1],
        [6, 9, 4]],

       [[6, 3, 2],
        [4, 2, 7],
        [8, 8, 6]]])

In [47]:
arr[0]

np.int64(1)

In [48]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr_3d[0][0]

array([1, 2, 3])

In [51]:
arr_3d[1][1][1]

np.int64(4)

In [52]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [5, 4, 2],
        [9, 8, 7]]])

In [53]:
arr_3d[1][1][0]

np.int64(5)

In [54]:
arr_3d[1][1][2] = 4

In [55]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [5, 4, 4],
        [9, 8, 7]]])

In [66]:
arr_3d[1,1,0]

np.int64(5)

In [76]:
arr_3d[[1,1,1]]

array([[[0, 1, 2],
        [5, 4, 4],
        [9, 8, 7]],

       [[0, 1, 2],
        [5, 4, 4],
        [9, 8, 7]],

       [[0, 1, 2],
        [5, 4, 4],
        [9, 8, 7]]])

In [71]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [5, 4, 4],
        [9, 8, 7]]])

In [77]:
arr_3d.ndim

3

In [79]:
arr_3d[0:]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [5, 4, 4],
        [9, 8, 7]]])

In [80]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr_3d[0,0]

array([1, 2, 3])

In [83]:
arr_2d

array([[1, 2],
       [3, 4]])

In [87]:
arr_2d[1,-1]

np.int64(4)

In [94]:
arr_3d[[0,1],[1,2],[1,2]]

array([5, 7])

In [96]:
arr_3d[0,[1,2],[1,0]]

array([5, 7])

In [107]:
arr_3d[0,0:2,0:2]

array([[1, 2],
       [4, 5]])

In [109]:
test_arr = np.random.randint(low = 0, high = 4, size = (2,2))

In [110]:
test_arr

array([[2, 1],
       [0, 3]])

In [111]:
test_arr + 1

array([[3, 2],
       [1, 4]])

In [112]:
test_arr * 2

array([[4, 2],
       [0, 6]])

In [113]:
test_arr / 2

array([[1. , 0.5],
       [0. , 1.5]])

In [115]:
test = np.array([[10,10],[10,10]])

In [116]:
test_arr @ test

array([[30, 30],
       [30, 30]])

In [117]:
test_arr

array([[2, 1],
       [0, 3]])

In [118]:
dailywts = 185 - np.arange(5*7)/5

In [119]:
185 - np.arange(35)/5

array([185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8, 183.6, 183.4,
       183.2, 183. , 182.8, 182.6, 182.4, 182.2, 182. , 181.8, 181.6,
       181.4, 181.2, 181. , 180.8, 180.6, 180.4, 180.2, 180. , 179.8,
       179.6, 179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2])

In [120]:
dailywts

array([185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8, 183.6, 183.4,
       183.2, 183. , 182.8, 182.6, 182.4, 182.2, 182. , 181.8, 181.6,
       181.4, 181.2, 181. , 180.8, 180.6, 180.4, 180.2, 180. , 179.8,
       179.6, 179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2])

In [126]:
avg = (dailywts[5::7] + dailywts[6::7]) / 2

In [127]:
avg

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [128]:
np.random.seed(5555)

In [129]:
gold = np.random.randint(low = 0, high = 10, size = (7,7))

In [131]:
loc = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [132]:
loc[:,0]

array([0, 2, 2, 5, 6])

In [133]:
loc[:,1]

array([4, 2, 3, 1, 3])

In [134]:
gold[0,4]

np.int64(2)

In [136]:
sum(gold[loc[:,0],loc[:,1]])

np.int64(20)

In [138]:
chic_fil_a = np.linspace([17,32],[28,36], num = 3, axis = 1)

In [140]:
every_dist = np.abs(chic_fil_a - 30)

In [141]:
c_dist = every_dist[[0,1],[2,0]]

In [143]:
c_dist

array([2., 2.])